### PR TITLE
Another style and formatting update. Also removed some unneeded files.

### PR DESCRIPTION
**Pull request by PyroSamurai**
Moved majority of styling to style.css. Removed unneeded files.
Fixed annoying issue with cursor changing over words in header.
Updated tags where proper or a html5 tag was available.
Lots of reformatting for readability and to get under 90 columns.
Add alt attributes that I missed last time.
Shortened some alt descriptions, b/c they were overly descriptive.
And anything else I might have forgotten to mention.

### CODE REVIEW

**Comment by Ablu** [comment]
Merged. Thanks a lot! Note that usually commit messages should not have a trailing "." in the first line since the first line is considered as summary of the whole commit. (And well summaries have no trailing "." :))

**Comment by bjorn** [comment]
To be a bit more accurate, the first line is the topic / title and they don't have trailing ".". Summaries usually do. ;-)

**Comment by PyroSamurai** [comment]
Could you link me to some images of how this is suppose to be done via terminal? Since to me this is all just packed into a single git commit message. I'm generally a verbose describer.

**Comment by bjorn** [comment]
See http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

He does call the first line the "summary", but this line is used here on github as a title and is commonly used in emails as the topic. Nitpicking about it having a dot or not at the end is a trait that I think @Ablu unfortunately learned from me. :-P

**Comment by PyroSamurai** [comment]
oh okay. Thanks :3

**Pull request merged**
